### ISSUE TITLE
Turn queries into objects, generate SQL only when assembly complete

### ISSUE THREAD

**Issue by nbenn** [nbenn/sqlr#3]
@krlmlr I think you're right in that I should first collect all the bits and pieces, defining the query in a list/object and only generate the SQL at the end, just before it is executed.

Should I stick with S3? I might run into a multiple dispatch situation:
```r
col <- col_int(min = 0L, max = 256L)
to_sql(col, con)
```
`col_int()` would not depend on a `con` object, but represent an INT column irrespective of db backend, the behaviour of `create_sql()` otoh would depend on both the object for which it is rendering SQL *and* the dialect of SQL.

I had considered R6 for something like
```r
Int <- R6::R6Class("Int", list(
  min = 0L,
  max = 256L,
  to_sql = function(con) UseMethod("to_sql", con),
  to_sql.con_a = function(con)
    paste0("<", con, "> ", self$min, ", ", self$max),
  to_sql.con_b = function(con)
    paste0("<", con, "> ", self$max, ", ", self$min)
  )
)

con <- structure("con", class = "con_a")

x <- Int$new()
x$to_sql(con)
```
But such behaviour [is not natively supported](https://stackoverflow.com/questions/25138436/r-r6-classes-and-usemethod-generic-methods).

Do you think it could be worthwhile to consider S4?

**Comment by krlmlr** [comment]
S3 seems way simpler. Dual dispatch can be emulated, I remember seeing this in dbplyr but I'm not sure. Something like the following would do here (assuming your column class is called `"col"`):

```r
to_sql <- function(obj, con) UseMethod("to_sql", obj)
to_sql.col <- function(col, con) col_to_sql(con, col)
col_to_sql <- function(con, col) UseMethod("col_to_sql", con)
col_to_sql.MariaDBConnection <- function(con, col) ...
```

There may be other advantages when using S4, though.

**Comment by krlmlr** [comment]
Is this completed now?

**Comment by nbenn** [comment]
Sorry for the delay. The problem is that `devtools::check()` doesn't appreciate our `list2env()` trick. The easiest way to silence the resulting check notes is keeping the `sqlr` objects as lists and access the lists fields explicitly. Or do you have an alternative suggestion?

https://github.com/nbenn/sqlr/blob/58114005160183a7ed92e2187f981109f5381962/R/spec-col.R#L335-L345

This (unsurprisingly) will generate notes as

```
sqlr_render.sqlr_col_chr.MariaDBConnection: no visible binding for
  global variable 'fixed'
sqlr_render.sqlr_col_chr.MariaDBConnection: no visible binding for
  global variable 'force_text'
...
```

**Comment by krlmlr** [comment]
We could use `utils::globalVariables()`, or make the names explicit. For the latter, the following could reduce manual work:

1. Implement a custom version of `list2env()` that generates substitute code. If the list contains elements named `n_elem`, `strict` and `allow_na`, the following code would be generated:

    ```r
    n_elem <- x$n_elem
    strict <- x$strict
    allow_na <- x$allow_na
    ```

    The generated code could be placed on the clipboard with _clipr_.

2. Run the code so that each instance of `list2env()` is touched, and substitute with the generated code.

**Comment by nbenn** [comment]
I'm looking into it now. I'd rather not go the `utils::globalVariables()` route, if that's ok with you.

**Comment by nbenn** [comment]
Done.
